-- CreateEnum
CREATE TYPE "ExpenseSubCategory" AS ENUM ('FAMILY', 'GROCERY', 'VEGETABLES_FRUITS', 'MAINTENANCE', 'RECHARGE', 'IGL', 'CLOTHS', 'MEDICAL', 'EMI', 'MAID', 'VEHICLE', 'GIFTS', 'TRAVELS', 'INVESTMENT', 'LIC', 'PERSONAL_OTHER', 'SALARY', 'MARKETING', 'INCENTIVE', 'STATIONERY', 'MISCELLANEOUS', 'MOBILE_RECHARGE', 'WIFI_RECHARGE', 'OFFICE_EXPENSE', 'CONVEYANCE', 'ELECTRICITY', 'OFFICE_MAINTENANCE', 'OFFICE_OTHER');

-- AlterTable
ALTER TABLE "expenses" ADD COLUMN     "subCategory" "ExpenseSubCategory";
